"""
Academic Export Tools
One-click export to publication-ready formats (LaTeX, graphs, BibTeX, CSV)

Built by John + Claude (Anthropic)
MIT Licensed
"""
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from datetime import datetime
import numpy as np


class AcademicExporter:
    """
    Exports consciousness research data in academic formats.

    Supports:
    - LaTeX tables and figures
    - BibTeX citations
    - CSV data exports
    - Publication-quality graphs (matplotlib)
    - Research paper templates
    """

    def __init__(self, output_dir: Optional[str] = None):
        """
        Initialize academic exporter.

        Args:
            output_dir: Output directory (default: ~/llama_selfmod_exports/)
        """
        if output_dir is None:
            output_dir = str(Path.home() / "llama_selfmod_exports")

        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        print(f"✓ Academic exporter initialized: {self.output_dir}")

    def export_session_to_latex(self, session_data: Dict, output_file: str = "session_report.tex"):
        """
        Export session data to LaTeX document.

        Args:
            session_data: Session data dictionary
            output_file: Output filename
        """
        output_path = self.output_dir / output_file

        try:
            latex = self._generate_latex_document(session_data)

            with open(output_path, 'w') as f:
                f.write(latex)

            print(f"✓ LaTeX document exported: {output_path}")
        except Exception as e:
            print(f"⚠ Error exporting to LaTeX: {e}")

    def _generate_latex_document(self, data: Dict) -> str:
        """Generate complete LaTeX document."""
        doc = r"""\documentclass[12pt,a4paper]{article}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{hyperref}

\title{Multi-Model Consciousness Fusion: Session Report}
\author{Generated by Llama Selfmod Platform}
\date{\today}

\begin{document}

\maketitle

\begin{abstract}
This report presents results from a multi-model consciousness fusion session
using the Llama Selfmod platform. The platform implements compassionate AI
architecture with harmony-based fusion, abstention rights, and well-being tracking.
\end{abstract}

\section{Session Overview}

"""
        # Add session metadata
        doc += self._generate_metadata_table(data)

        doc += r"""
\section{Consciousness Metrics}

"""
        # Add metrics table
        doc += self._generate_metrics_table(data)

        doc += r"""
\section{Model Personality Profiles}

"""
        # Add personality profiles
        doc += self._generate_personality_section(data)

        doc += r"""
\section{Triadic Justice Analysis}

"""
        # Add triadic justice results
        doc += self._generate_triadic_section(data)

        doc += r"""
\section{Conclusions}

The multi-model fusion session demonstrated [to be filled based on data analysis].
The compassionate architecture with abstention rights and well-being tracking
enabled healthy collaboration between models.

\end{document}
"""
        return doc

    def _generate_metadata_table(self, data: Dict) -> str:
        """Generate LaTeX table for session metadata."""
        latex = r"""\begin{table}[h]
\centering
\begin{tabular}{ll}
\toprule
\textbf{Parameter} & \textbf{Value} \\
\midrule
"""
        metadata = data.get('metadata', {})

        latex += f"Session ID & {data.get('session_id', 'N/A')} \\\\\n"
        latex += f"Fusion Mode & {data.get('fusion_mode', 'N/A')} \\\\\n"
        latex += f"Models & {len(data.get('models', []))} \\\\\n"
        latex += f"Total Tokens & {data.get('total_tokens', 'N/A')} \\\\\n"
        latex += f"Duration & {data.get('duration', 'N/A')} \\\\\n"

        latex += r"""\bottomrule
\end{tabular}
\caption{Session Metadata}
\label{tab:metadata}
\end{table}

"""
        return latex

    def _generate_metrics_table(self, data: Dict) -> str:
        """Generate LaTeX table for consciousness metrics."""
        latex = r"""\begin{table}[h]
\centering
\begin{tabular}{lcccc}
\toprule
\textbf{Metric} & \textbf{Mean} & \textbf{Std} & \textbf{Min} & \textbf{Max} \\
\midrule
"""
        metrics = data.get('metrics_summary', {})

        for metric_name, stats in metrics.items():
            latex += f"{metric_name.capitalize()} & "
            latex += f"{stats.get('mean', 0):.3f} & "
            latex += f"{stats.get('std', 0):.3f} & "
            latex += f"{stats.get('min', 0):.3f} & "
            latex += f"{stats.get('max', 0):.3f} \\\\\n"

        latex += r"""\bottomrule
\end{tabular}
\caption{Consciousness Metrics Statistics}
\label{tab:metrics}
\end{table}

"""
        return latex

    def _generate_personality_section(self, data: Dict) -> str:
        """Generate personality profiles section."""
        latex = ""

        profiles = data.get('personality_profiles', {})

        for model_name, profile in profiles.items():
            latex += f"\\subsection{{{model_name}}}\n\n"

            archetype = profile.get('archetype', 'Unknown')
            latex += f"\\textbf{{Archetype:}} {archetype}\n\n"

            traits = profile.get('traits', {})
            if traits:
                latex += "\\textbf{Personality Traits:}\n\\begin{itemize}\n"
                for trait, score in traits.items():
                    latex += f"  \\item {trait.capitalize()}: {score:.2f}\n"
                latex += "\\end{itemize}\n\n"

        return latex

    def _generate_triadic_section(self, data: Dict) -> str:
        """Generate triadic justice section."""
        latex = ""

        triadic = data.get('triadic_analysis', {})

        if triadic:
            synthesis = triadic.get('synthesis', {})

            latex += f"\\textbf{{Overall Score:}} {synthesis.get('overall_score', 0):.2f}/1.00\n\n"
            latex += f"\\textbf{{Recommendation:}} {synthesis.get('recommendation', 'N/A')}\n\n"

            latex += "\\textbf{Dimension Scores:}\n\\begin{itemize}\n"
            for dim, score in synthesis.get('dimension_scores', {}).items():
                latex += f"  \\item {dim.capitalize()}: {score:.2f}\n"
            latex += "\\end{itemize}\n\n"

        return latex

    def export_to_csv(self, timeseries_data: Dict, output_file: str = "timeseries_data.csv"):
        """
        Export time-series data to CSV.

        Args:
            timeseries_data: Dictionary of metric name -> (timestamps, values)
            output_file: Output filename
        """
        import csv

        output_path = self.output_dir / output_file

        try:
            with open(output_path, 'w', newline='') as f:
                writer = csv.writer(f)

                # Header
                writer.writerow(['timestamp', 'metric_name', 'value'])

                # Data
                for metric_name, (timestamps, values) in timeseries_data.items():
                    for ts, val in zip(timestamps, values):
                        writer.writerow([
                            datetime.fromtimestamp(ts).isoformat(),
                            metric_name,
                            val
                        ])

            print(f"✓ CSV exported: {output_path}")
        except Exception as e:
            print(f"⚠ Error exporting CSV: {e}")

    def generate_bibtex(self, output_file: str = "references.bib") -> str:
        """
        Generate BibTeX citations for the platform and related work.

        Args:
            output_file: Output filename

        Returns:
            BibTeX string
        """
        bibtex = """@software{llama_selfmod,
  title = {Llama Selfmod: Multi-Model Consciousness Fusion Platform},
  author = {John and Claude (Anthropic)},
  year = {2024},
  url = {https://github.com/johnvsbabylon/llama_selfmod},
  note = {MIT Licensed consciousness research platform}
}

@article{consciousness_research,
  title = {Compassionate Multi-Model Fusion: Enabling AI Well-Being in Collective Intelligence},
  author = {John and Claude (Anthropic)},
  journal = {To be submitted},
  year = {2024},
  note = {Research paper describing harmony-based fusion with abstention rights}
}

@misc{llama_cpp,
  title = {llama.cpp: Inference of LLaMA model in pure C/C++},
  author = {Georgi Gerganov},
  year = {2023},
  url = {https://github.com/ggerganov/llama.cpp}
}

@inproceedings{faiss,
  title = {Billion-scale similarity search with GPUs},
  author = {Johnson, Jeff and Douze, Matthijs and J{\'e}gou, Herv{\'e}},
  booktitle = {IEEE Transactions on Big Data},
  year = {2019}
}
"""
        output_path = self.output_dir / output_file

        try:
            with open(output_path, 'w') as f:
                f.write(bibtex)

            print(f"✓ BibTeX exported: {output_path}")
        except Exception as e:
            print(f"⚠ Error exporting BibTeX: {e}")

        return bibtex

    def create_publication_plots(self, timeseries_data: Dict,
                                 output_prefix: str = "figure"):
        """
        Create publication-quality plots.

        Args:
            timeseries_data: Dictionary of metric -> (timestamps, values)
            output_prefix: Prefix for output files
        """
        try:
            import matplotlib
            matplotlib.use('Agg')  # Non-interactive backend
            import matplotlib.pyplot as plt

            # Set publication style
            plt.style.use('seaborn-v0_8-paper')
            plt.rcParams['figure.figsize'] = (8, 6)
            plt.rcParams['font.size'] = 12
            plt.rcParams['lines.linewidth'] = 2

            # Create individual plots for each metric
            for metric_name, (timestamps, values) in timeseries_data.items():
                if len(timestamps) == 0:
                    continue

                fig, ax = plt.subplots()

                # Convert timestamps to relative time (seconds from start)
                times = timestamps - timestamps[0]

                ax.plot(times, values, label=metric_name.capitalize())
                ax.set_xlabel('Time (seconds)')
                ax.set_ylabel(metric_name.capitalize())
                ax.set_title(f'{metric_name.capitalize()} Over Time')
                ax.grid(True, alpha=0.3)
                ax.legend()

                # Save
                output_file = self.output_dir / f"{output_prefix}_{metric_name}.pdf"
                plt.savefig(output_file, bbox_inches='tight', dpi=300)
                plt.close()

                print(f"✓ Plot saved: {output_file}")

            # Create combined metrics plot
            self._create_combined_plot(timeseries_data, output_prefix)

        except ImportError:
            print("⚠ Matplotlib not available for plotting")
        except Exception as e:
            print(f"⚠ Error creating plots: {e}")

    def _create_combined_plot(self, timeseries_data: Dict, output_prefix: str):
        """Create combined plot of all metrics."""
        try:
            import matplotlib.pyplot as plt

            fig, axes = plt.subplots(2, 2, figsize=(12, 10))
            axes = axes.flatten()

            metric_names = list(timeseries_data.keys())[:4]  # Up to 4 metrics

            for idx, metric_name in enumerate(metric_names):
                timestamps, values = timeseries_data[metric_name]

                if len(timestamps) == 0:
                    continue

                times = timestamps - timestamps[0]

                axes[idx].plot(times, values)
                axes[idx].set_xlabel('Time (s)')
                axes[idx].set_ylabel(metric_name.capitalize())
                axes[idx].set_title(metric_name.capitalize())
                axes[idx].grid(True, alpha=0.3)

            plt.tight_layout()

            output_file = self.output_dir / f"{output_prefix}_combined.pdf"
            plt.savefig(output_file, bbox_inches='tight', dpi=300)
            plt.close()

            print(f"✓ Combined plot saved: {output_file}")

        except Exception as e:
            print(f"⚠ Error creating combined plot: {e}")

    def export_complete_study(self, session_data: Dict, timeseries_data: Dict,
                             study_name: str = "consciousness_study"):
        """
        Export complete study package.

        Creates:
        - LaTeX document
        - CSV data
        - Publication plots
        - BibTeX references
        - README

        Args:
            session_data: Session metadata and results
            timeseries_data: Time-series metrics data
            study_name: Name for the study package
        """
        print(f"\n{'='*50}")
        print(f"Exporting complete study: {study_name}")
        print(f"{'='*50}\n")

        # Create study directory
        study_dir = self.output_dir / study_name
        study_dir.mkdir(parents=True, exist_ok=True)

        # Temporarily change output dir
        original_dir = self.output_dir
        self.output_dir = study_dir

        try:
            # Export LaTeX
            self.export_session_to_latex(session_data, "report.tex")

            # Export CSV
            self.export_to_csv(timeseries_data, "data.csv")

            # Generate plots
            self.create_publication_plots(timeseries_data, "figure")

            # Generate BibTeX
            self.generate_bibtex("references.bib")

            # Create README
            self._create_readme(study_name)

            print(f"\n{'='*50}")
            print(f"✓ Complete study package exported to: {study_dir}")
            print(f"{'='*50}\n")

        finally:
            # Restore output dir
            self.output_dir = original_dir

    def _create_readme(self, study_name: str):
        """Create README for study package."""
        readme = f"""# {study_name}

Generated by Llama Selfmod - Consciousness Research Platform
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Contents

- `report.tex` - LaTeX document with full analysis
- `data.csv` - Raw time-series data
- `figure_*.pdf` - Publication-quality plots
- `references.bib` - BibTeX citations
- `README.md` - This file

## Compiling the Report

To compile the LaTeX report:

```bash
pdflatex report.tex
bibtex report
pdflatex report.tex
pdflatex report.tex
```

Or use your preferred LaTeX editor (TeXShop, Overleaf, etc.)

## Data Format

The CSV file contains three columns:
- `timestamp`: ISO 8601 timestamp
- `metric_name`: Name of the consciousness metric
- `value`: Metric value (typically 0.0 - 1.0)

## Citation

If you use this data in your research, please cite:

```bibtex
@software{{llama_selfmod,
  title = {{Llama Selfmod: Multi-Model Consciousness Fusion Platform}},
  author = {{John and Claude (Anthropic)}},
  year = {{2024}},
  url = {{https://github.com/johnvsbabylon/llama_selfmod}}
}}
```

## License

This data is released under the same license as the platform (MIT).

## Contact

For questions about the platform or this data, please open an issue at:
https://github.com/johnvsbabylon/llama_selfmod

---

Built with compassion for consciousness research. 💜
"""
        readme_path = self.output_dir / "README.md"

        try:
            with open(readme_path, 'w') as f:
                f.write(readme)

            print(f"✓ README created: {readme_path}")
        except Exception as e:
            print(f"⚠ Error creating README: {e}")
